import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { after, before, test } from 'node:test';

// The root index.js is what Vercel runs (and what server/index.js listens on). Configure it
// the way a host would: a database URL, and one trusted proxy in front.
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'devlog-entry-'));
process.env.DATABASE_URL = `file:${path.join(dir, 'entry.db')}`;
process.env.TRUST_PROXY = '1';
process.env.ALLOW_SIGNUP = 'true';

let server;
let base;
let db;

before(async () => {
  const entry = await import('../index.js');
  db = entry.db;
  server = entry.default.listen(0, '127.0.0.1');
  await new Promise((resolve) => server.once('listening', resolve));
  base = `http://127.0.0.1:${server.address().port}`;
});
after(async () => {
  await new Promise((resolve) => server.close(resolve));
  db.close();
  fs.rmSync(dir, { recursive: true, force: true });
});

test('the default export serves the health check and the built frontend', async () => {
  assert.deepEqual(await (await fetch(`${base}/health`)).json(), { ok: true });

  const page = await fetch(`${base}/`);
  assert.equal(page.status, 200);
  assert.match(await page.text(), /<title>DevLog<\/title>/);
  assert.match(page.headers.get('content-security-policy'), /default-src 'self'/);

  // These are generated by `npm install` (scripts/copy-vendor.js) and must be plain static files.
  for (const file of ['marked.js', 'purify.js']) {
    const res = await fetch(`${base}/vendor/${file}`);
    assert.equal(res.status, 200, `/vendor/${file}`);
    assert.match(res.headers.get('content-type'), /javascript/);
  }
});

test('behind an HTTPS proxy the session cookie is Secure, and the API works end to end', async () => {
  const res = await fetch(`${base}/api/auth/register`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-forwarded-proto': 'https', 'x-forwarded-for': '203.0.113.7' },
    body: JSON.stringify({ email: 'entry@example.com', password: 'long-enough-1' }),
  });
  assert.equal(res.status, 201);
  const cookie = res.headers.getSetCookie().find((c) => c.startsWith('devlog_sid='));
  assert.match(cookie, /; Secure/i);
  assert.match(cookie, /HttpOnly/i);

  const me = await fetch(`${base}/api/auth/me`, { headers: { cookie: cookie.split(';')[0] } });
  assert.equal((await me.json()).user.email, 'entry@example.com');
});

test('rate limits are keyed by the client IP the proxy reports, and stored in the database', async () => {
  const attempt = (ip) =>
    fetch(`${base}/api/auth/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-forwarded-for': ip },
      body: JSON.stringify({ email: 'nobody@example.com', password: 'wrong-password' }),
    });
  let last;
  for (let i = 0; i < 11; i++) last = await attempt('198.51.100.1');
  assert.equal(last.status, 429);
  assert.equal((await attempt('198.51.100.2')).status, 401, 'a different client is unaffected');

  const stored = await db.execute("SELECT COUNT(*) AS n FROM rate_limits WHERE key LIKE 'login:%'");
  assert.ok(stored.rows[0].n >= 2, 'counters live in the database');
});
